import Head from 'next/head'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>noonoo clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h5>main page</h5>
        <h5>지금 나에게 필요한 인기 영상</h5>
        <h5>최신 드라마를 모두 감상해보세요</h5>
        <h5>알고보면 더욱 재밌는 영화</h5>
        <h5>당신의 웃음을 책임집니다</h5>
        <h5>추억의 애니와 최신애니를 한꺼번에</h5>
      </Layout>
    </div>
  )
}